apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-backend
  template:
    metadata:
      labels:
        app: payment-backend
    spec:
      containers:
        - name: payment-backend
          image: your-dockerhub-username/payment-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: production