apiVersion: v1
kind: Service
metadata:
  name: payment-backend-service
spec:
  type: NodePort
  selector:
    app: payment-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007  # You can access it via http://localhost:30007 when using Minikube